MR-1002: Backport for ShipmentFacade::findShipmentMethodByName
spryker/shipment pull request #3
Opened 2020-11-09 11:38 UTC by zssamoylov

* Developer(s): @zssamoylov
* Ticket: https://spryker.atlassian.net/browse/MR-1002
* Academy PR: TBD

#### Please confirm
* [ ]  No new OS components - or they have been approved by legal department

#### Documentation
* [ ]  Functional documentation provided or in progress?
* [ ]  Integration guide for projects provided or not needed?
* [ ]  Migration guides for all contained majors provided or not needed?

#### Release Table
 Module                | Release Type         | Constraint Updates         |
   :--------------------- | :------------------------ | :--------------------- |
   Shipment          | minor                 |                       |
#### Release Notes
Added shopping list back port. 

#### Module ShoppingList
##### Change log
Improvements
* Introduced `ShipmentFacade::findShipmentMethodByName()` to get shipment by method name.

2020-11-09 13:12 UTC, matweew requested changes

2020-11-09 13:12 UTC, matweew commented on src/Spryker/Zed/Shipment/Persistence/ShipmentPersistenceFactory.php
> +        return new ShipmentMethodMapper($this->createStoreRelationMapper());
you don't need store relationship support, see https://github.com/spryker/shipment/blob/7.0.0/src/Spryker/Zed/Shipment/Persistence/ShipmentPersistenceFactory.php#L96

2020-11-09 14:33 UTC, matweew approved these changes

2020-11-20 10:43 UTC, matweew commented
https://github.com/spryker/shipment/releases/tag/7.2.0

2020-11-20 10:43 UTC, closed without merging

2020-11-20 11:18 UTC, dereuromark commented
Is this backport attached to a RG? Please also link that one above.